server:
  port: 8080
spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
#H2 properties
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampledb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    mvc:
      pathmatch:
        matching-strategy: any-path-matcher 
#Eureka Properties      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost